# Generated by Django 5.2.7 on 2025-10-19 21:20

import sections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(upload_to=sections.models.hero_section_upload_to),
                ),
                ("headline", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("primary_button_text", models.CharField(max_length=255)),
                ("secondary_button_text", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
