# Generated by Django 5.2.7 on 2025-10-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
