# Generated by Django 5.2.8 on 2025-12-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0002_featuredproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroSection",
        ),
    ]
