# Generated by Django 5.2.7 on 2025-10-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0002_herosection_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="herosection",
            options={"ordering": ["order"]},
        ),
    ]
