# Generated by Django 5.2.7 on 2025-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0003_alter_herosection_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
