# Generated by Django 5.2.8 on 2025-12-02 01:34

import django.db.models.deletion
from django.db import migrations, models

import sections.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_producttype_is_digital_and_more"),
        ("sections", "0003_delete_herosection"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.IntegerField(default=0, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=sections.models.featured_category_upload_to,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
