# Generated by Django 5.2.7 on 2025-10-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0004_alter_herosection_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="herosection",
            options={},
        ),
    ]
