# Generated by Django 5.2.7 on 2025-10-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0005_alter_herosection_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="order",
        ),
        migrations.AddField(
            model_name="herosection",
            name="sort_order",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
