# Generated by Django 5.2.8 on 2025-11-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="is_digital",
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="is_shipping_required",
        ),
    ]
