# Generated by Django 5.2.7 on 2025-10-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariant_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_start",
            field=models.DecimalField(
                decimal_places=2, default="499.99", max_digits=10
            ),
        ),
    ]
