# Generated by Django 5.2.7 on 2025-10-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_price_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["title"],
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="name",
            new_name="title",
        ),
    ]
