# Generated by Django 5.2.7 on 2025-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_options_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="regular_price",
            field=models.DecimalField(decimal_places=2, default="1.11", max_digits=10),
            preserve_default=False,
        ),
    ]
