# Generated by Django 5.2.7 on 2025-11-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productvariant_regular_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="products.productvariant",
            ),
            preserve_default=False,
        ),
    ]
